#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=Train_GPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=gpt_generate_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
cd $HOME/uvadlc_practicals_2024/assignment2/part2/
# Activate your environment
source activate dl2024
# Run your code
srun python generate.py --temperature 1.0 --top_p 0.8 --prompt "Yesterday, I went to the store and bought some "