#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=AdAttack
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=attack_train_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Activate your environment
source activate dl2024
# train standard
srun python -u train.py

# train fgsm
srun python -u train.py --train_strats FGSM
# train pgd
srun python -u train.py --train_strats PGD
